CREATE TABLE IF NOT EXISTS "parent_stat_submissions" (
  "id" serial PRIMARY KEY NOT NULL,
  "parent_id" integer REFERENCES "parents"("id"),
  "player_id" integer REFERENCES "players"("id"),
  "athlete_email" text,
  "athlete_name" text NOT NULL,
  "athlete_dob" timestamp,
  "grad_year" integer,
  "position" text,
  "state" text,
  "division" text,
  "season" text,
  "passing_tds" integer,
  "rushing_tds" integer,
  "receiving_tds" integer,
  "defensive_tds" integer,
  "sacks" integer,
  "hers_rating" double precision,
  "forty_yard_dash" double precision,
  "vertical_jump" double precision,
  "shuttle_5_10_5" double precision,
  "source" text DEFAULT 'parent_portal',
  "notes" text,
  "status" text DEFAULT 'pending' NOT NULL,
  "submitted_at" timestamp DEFAULT now(),
  "reviewed_at" timestamp,
  "reviewed_by" integer
);
