CREATE TABLE IF NOT EXISTS "parent_stat_submissions" (
  "id" serial PRIMARY KEY NOT NULL,
  "parent_id" integer NOT NULL REFERENCES "parents"("id"),
  "player_id" integer NOT NULL REFERENCES "players"("id"),
  "verification_status" text NOT NULL DEFAULT 'pending',
  "season" text,
  "school" text,
  "email" text,
  "name" text,
  "dob" timestamp,
  "grad_year" integer,
  "position" text,
  "state" text,
  "division" text,
  "max_preps_url" text,
  "forty_yard_dash" text,
  "vertical_jump" text,
  "shuttle_5105" text,
  "broad_jump" text,
  "flag_pulls" integer,
  "touchdowns_passing" integer,
  "touchdowns_rushing" integer,
  "touchdowns_receiving" integer,
  "interceptions" integer,
  "sacks" double precision,
  "passing_yards" integer,
  "hers_rating" double precision,
  "admin_notes" text,
  "reviewed_at" timestamp,
  "reviewed_by" integer REFERENCES "admin_users"("id"),
  "created_at" timestamp DEFAULT now()
);
