CREATE TABLE IF NOT EXISTS "parent_stat_submissions" (
  "id" serial PRIMARY KEY NOT NULL,
  "parent_id" integer NOT NULL REFERENCES "parents"("id"),
  "player_id" integer NOT NULL REFERENCES "players"("id"),
  "verification_status" text NOT NULL DEFAULT 'pending',
  "season" text,
  "school" text,
  "email" text,
  "name" text,
  "dob" timestamp,
  "grad_year" integer,
  "position" text,
  "state" text,
  "division" text,
  "athlete_email" text,
  "athlete_name" text NOT NULL,
  "athlete_dob" timestamp,
  "max_preps_url" text,
  "forty_yard_dash" double precision,
  "vertical_jump" double precision,
  "shuttle_5_10_5" double precision,
  "broad_jump" text,
  "flag_pulls" integer,
  "touchdowns_passing" integer,
  "touchdowns_rushing" integer,
  "touchdowns_receiving" integer,
  "rushing_yards" integer,
  "receiving_yards" integer,
  "interceptions" integer,
  "sacks" integer,
  "passing_yards" integer,
  "hers_rating" double precision,
  "admin_notes" text,
  "reviewed_at" timestamp,
  "reviewed_by" integer REFERENCES "admin_users"("id"),
  "created_at" timestamp DEFAULT now(),
  "submitted_at" timestamp DEFAULT now(),
  "source" text DEFAULT 'parent_portal',
  "notes" text,
  "status" text DEFAULT 'pending' NOT NULL,
  "passing_tds" integer,
  "rushing_tds" integer,
  "receiving_tds" integer,
  "defensive_tds" integer
);
